hystrix:
  command:
    defaut:
      execution:
        isolation:
          thread:
            timeoutInMiliseconds: 2000
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    
  routes:
    auth-service:
      path: "/uaa/**"
      url: http://localhost:5000
      stripPrefix: false
      sensitiveHeaders:
    account-service:
        path: /accounts/**
        serviceId: account-service
        stripPrefix: false
        sensitiveHeaders:
server:
  port: 4000